[package]
name                 = "uasset-lens-material-analyzer"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
description.workspace = true
repository.workspace = true
homepage.workspace   = true
keywords.workspace   = true
categories.workspace = true
authors.workspace    = true

[dependencies]
uasset-lens-dependency-graph = { path = "../uasset-lens-dependency-graph" }
uasset-lens-scanner          = { path = "../uasset-lens-scanner" }
uasset-lens-shared           = { path = "../uasset-lens-shared" }
