[package]
name                 = "uasset-lens-material-analyzer"
publish             = false
version.workspace    = true
edition.workspace    = true
license.workspace    = true
description.workspace = true
repository.workspace = true
homepage.workspace   = true
keywords.workspace   = true
categories.workspace = true
authors.workspace    = true

[dependencies]
uasset-lens-dependency-graph = { workspace = true }
uasset-lens-scanner          = { workspace = true }
uasset-lens-shared           = { workspace = true }
