[package]
name     = "watcher"
publish  = false
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
notify              = { workspace = true }
thiserror           = { workspace = true }
tracing             = { workspace = true }
shared              = { path = "../shared" }
scanner             = { path = "../scanner" }
asset-db            = { path = "../asset-db" }
dependency-graph    = { path = "../dependency-graph" }
dead-asset-detector = { path = "../dead-asset-detector" }
