[package]
name    = "asset-db"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
test-support = ["scanner/test-support"]

[dependencies]
shared     = { path = "../shared" }
scanner    = { path = "../scanner" }
rusqlite   = { workspace = true, features = ["bundled"] }
serde_json = { workspace = true }
thiserror  = { workspace = true }
globset    = { workspace = true }

[dev-dependencies]
scanner = { path = "../scanner", features = ["test-support"] }
