[package]
name    = "cli"
version.workspace = true
edition.workspace = true

[dependencies]
shared              = { path = "../shared" }
scanner             = { path = "../scanner" }
asset-db            = { path = "../asset-db" }
dependency-graph    = { path = "../dependency-graph" }
dead-asset-detector  = { path = "../dead-asset-detector" }
duplicate-detector  = { path = "../duplicate-detector" }
redirector-analyzer  = { path = "../redirector-analyzer" }
lint-engine         = { path = "../lint-engine" }
budget-tracker      = { path = "../budget-tracker" }
clap       = { workspace = true }
anyhow     = { workspace = true }
tracing    = { workspace = true }
walkdir    = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
toml       = { workspace = true }
