[package]
name                 = "uasset-lens-git-diff"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
description          = "Diff Unreal Engine 5 assets between Git HEAD and the working tree"
repository.workspace = true
homepage.workspace   = true
keywords.workspace   = true
categories.workspace = true
authors.workspace    = true

[dependencies]
uasset-lens-shared  = { workspace = true }
uasset-lens-scanner = { workspace = true }
thiserror           = { workspace = true }
tracing             = { workspace = true }
tempfile            = { workspace = true }
