[package]
name                 = "uasset-lens-budget-tracker"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
description.workspace = true
repository.workspace = true
homepage.workspace   = true
keywords.workspace   = true
categories.workspace = true
authors.workspace    = true

[dependencies]
uasset-lens-asset-db = { workspace = true }
uasset-lens-shared   = { workspace = true }
serde                = { workspace = true }

[dev-dependencies]
uasset-lens-asset-db = { workspace = true, features = ["test-support"] }
