[package]
name                 = "cli"
publish             = false
version.workspace    = true
edition.workspace    = true
license.workspace    = true
description.workspace = true
repository.workspace = true
homepage.workspace   = true
keywords.workspace   = true
categories.workspace = true
authors.workspace    = true

[[bin]]
name = "uasset-lens"
path = "src/main.rs"

[dependencies]
uasset-lens-shared              = { workspace = true }
uasset-lens-scanner             = { workspace = true }
uasset-lens-asset-db            = { workspace = true }
uasset-lens-dependency-graph    = { workspace = true }
uasset-lens-analysis            = { workspace = true }
uasset-lens-watcher             = { workspace = true }
ctrlc      = { workspace = true }
clap       = { workspace = true }
anyhow     = { workspace = true }
tracing    = { workspace = true }
walkdir    = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
toml       = { workspace = true }
globset    = { workspace = true }
clap_complete = "4.6.5"

[dev-dependencies]
uasset-lens-scanner  = { workspace = true, features = ["test-support"] }
uasset-lens-asset-db = { workspace = true, features = ["test-support"] }
