[package]
name                 = "uasset-lens-lint-engine"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
description.workspace = true
repository.workspace = true
homepage.workspace   = true
keywords.workspace   = true
categories.workspace = true
authors.workspace    = true

[dependencies]
uasset-lens-asset-db    = { path = "../uasset-lens-asset-db" }
uasset-lens-bp-analyzer = { path = "../uasset-lens-bp-analyzer" }
uasset-lens-scanner     = { path = "../uasset-lens-scanner" }
uasset-lens-shared      = { path = "../uasset-lens-shared" }
