use std::path::Path;

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub struct AssetPath(String);

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum AssetPathError {
    #[error("asset path must not be empty")]
    Empty,
    #[error("asset path must start with '/'")]
    MissingLeadingSlash,
    #[error("asset path must not contain a file extension (found '.' after last '/')")]
    InvalidCharacter,
    #[error("file path is not under the content root")]
    NotUnderContentRoot,
}

impl AssetPath {
    pub fn new(s: &str) -> Result<Self, AssetPathError> {
        if s.is_empty() {
            return Err(AssetPathError::Empty);
        }
        if !s.starts_with('/') {
            return Err(AssetPathError::MissingLeadingSlash);
        }
        let last_segment = s.rsplit('/').next().unwrap_or("");
        if last_segment.contains('.') {
            return Err(AssetPathError::InvalidCharacter);
        }
        Ok(Self(s.to_owned()))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }

    pub fn from_fs_path(content_root: &Path, file_path: &Path) -> Result<Self, AssetPathError> {
        let canonical_root = content_root
            .canonicalize()
            .map_err(|_| AssetPathError::NotUnderContentRoot)?;
        Self::from_fs_path_with_canonical_root(&canonical_root, file_path)
    }

    /// Like [`from_fs_path`](Self::from_fs_path) but takes an already-canonicalized content root,
    /// skipping the root `canonicalize()` syscall. Hot-path callers (the scanner's per-file loop)
    /// canonicalize the root once per scan and reuse it across every asset.
    ///
    /// The caller is responsible for passing a canonical root; a non-canonical root only ever
    /// causes `strip_prefix` to over-reject (returning `NotUnderContentRoot`), never to admit a
    /// path that escapes the root, so the traversal defense degrades safely.
    pub fn from_fs_path_with_canonical_root(
        canonical_root: &Path,
        file_path: &Path,
    ) -> Result<Self, AssetPathError> {
        // Resolve symlinks to verify the real file lives under content_root.
        // For files that no longer exist on disk (stale assets being cleaned up),
        // canonicalize the parent directory instead so the prefix still aligns with
        // canonical_root on all platforms (e.g. Windows \\?\ extended paths).
        let canonical_file = file_path.canonicalize().unwrap_or_else(|_| {
            file_path
                .parent()
                .and_then(|p| p.canonicalize().ok())
                .map(|p| p.join(file_path.file_name().unwrap_or_default()))
                .unwrap_or_else(|| file_path.to_path_buf())
        });
        let relative = canonical_file
            .strip_prefix(canonical_root)
            .map_err(|_| AssetPathError::NotUnderContentRoot)?;

        let without_ext = relative.with_extension("");

        let game_path = format!(
            "/Game/{}",
            without_ext
                .components()
                .map(|c| c.as_os_str().to_string_lossy())
                .collect::<Vec<_>>()
                .join("/")
        );

        Ok(Self(game_path))
    }

    pub fn package_name(&self) -> &str {
        match self.0.rfind('/') {
            None => &self.0,
            Some(slash_pos) => {
                let last = &self.0[slash_pos + 1..];
                match last.find('.') {
                    None => &self.0,
                    Some(dot_pos) => &self.0[..slash_pos + 1 + dot_pos],
                }
            }
        }
    }
}

// OFPA (One File Per Actor) assets are generated by UE5 World Partition and are never
// referenced in import tables — they are loaded internally by the engine.
pub fn is_ofpa_path(path: &str) -> bool {
    path.contains("/__ExternalActors__/") || path.contains("/__ExternalObjects__/")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_should_return_error_for_empty_string() {
        assert_eq!(AssetPath::new(""), Err(AssetPathError::Empty));
    }

    #[test]
    fn new_should_return_error_when_missing_leading_slash() {
        assert_eq!(
            AssetPath::new("Game/Characters/BP_Player"),
            Err(AssetPathError::MissingLeadingSlash)
        );
    }

    #[test]
    fn new_should_return_error_when_path_contains_extension() {
        assert_eq!(
            AssetPath::new("/Game/Characters/BP_Player.uasset"),
            Err(AssetPathError::InvalidCharacter)
        );
    }

    #[test]
    fn new_should_succeed_for_valid_path() {
        let path = AssetPath::new("/Game/Characters/BP_Player").unwrap();
        assert_eq!(path.as_str(), "/Game/Characters/BP_Player");
    }

    #[test]
    fn from_fs_path_should_convert_uasset_path_to_game_path() {
        let dir = std::env::temp_dir().join(format!("uasset_from_fs_{}", std::process::id()));
        let content_root = dir.join("Content");
        let chars_dir = content_root.join("Characters");
        std::fs::create_dir_all(&chars_dir).unwrap();
        let file_path = chars_dir.join("BP_Player.uasset");
        std::fs::write(&file_path, b"").unwrap();

        let path = AssetPath::from_fs_path(&content_root, &file_path).unwrap();
        let _ = std::fs::remove_dir_all(&dir);
        assert_eq!(path.as_str(), "/Game/Characters/BP_Player");
    }

    #[test]
    fn from_fs_path_should_return_error_when_not_under_content_root() {
        let dir = std::env::temp_dir().join(format!("uasset_outside_{}", std::process::id()));
        let content_root = dir.join("Content");
        let other_dir = dir.join("Other").join("Characters");
        std::fs::create_dir_all(&content_root).unwrap();
        std::fs::create_dir_all(&other_dir).unwrap();
        let file_path = other_dir.join("BP_Player.uasset");
        std::fs::write(&file_path, b"").unwrap();

        let result = AssetPath::from_fs_path(&content_root, &file_path);
        let _ = std::fs::remove_dir_all(&dir);
        assert_eq!(result, Err(AssetPathError::NotUnderContentRoot));
    }

    #[test]
    fn from_fs_path_with_canonical_root_should_match_from_fs_path() {
        let dir = std::env::temp_dir().join(format!("uasset_canon_match_{}", std::process::id()));
        let content_root = dir.join("Content");
        let chars_dir = content_root.join("Characters");
        std::fs::create_dir_all(&chars_dir).unwrap();
        let file_path = chars_dir.join("BP_Player.uasset");
        std::fs::write(&file_path, b"").unwrap();

        let canonical_root = content_root.canonicalize().unwrap();
        let via_canonical =
            AssetPath::from_fs_path_with_canonical_root(&canonical_root, &file_path).unwrap();
        let via_full = AssetPath::from_fs_path(&content_root, &file_path).unwrap();
        let _ = std::fs::remove_dir_all(&dir);
        assert_eq!(via_canonical, via_full);
        assert_eq!(via_canonical.as_str(), "/Game/Characters/BP_Player");
    }

    #[test]
    fn from_fs_path_with_canonical_root_should_reject_path_outside_root() {
        let dir = std::env::temp_dir().join(format!("uasset_canon_outside_{}", std::process::id()));
        let content_root = dir.join("Content");
        let other_dir = dir.join("Other");
        std::fs::create_dir_all(&content_root).unwrap();
        std::fs::create_dir_all(&other_dir).unwrap();
        let file_path = other_dir.join("BP_Player.uasset");
        std::fs::write(&file_path, b"").unwrap();

        let canonical_root = content_root.canonicalize().unwrap();
        let result = AssetPath::from_fs_path_with_canonical_root(&canonical_root, &file_path);
        let _ = std::fs::remove_dir_all(&dir);
        assert_eq!(result, Err(AssetPathError::NotUnderContentRoot));
    }

    #[test]
    #[cfg(unix)]
    fn from_fs_path_should_return_error_for_symlink_outside_content_root() {
        use std::os::unix::fs::symlink;

        let dir = std::env::temp_dir().join(format!("uasset_symlink_{}", std::process::id()));
        let content_root = dir.join("Content");
        let outside_dir = dir.join("Outside");
        std::fs::create_dir_all(&content_root).unwrap();
        std::fs::create_dir_all(&outside_dir).unwrap();

        let real_file = outside_dir.join("Secret.uasset");
        std::fs::write(&real_file, b"").unwrap();

        // Symlink inside content_root whose target resolves to outside content_root
        let link_path = content_root.join("FakeAsset.uasset");
        symlink(&real_file, &link_path).unwrap();

        let result = AssetPath::from_fs_path(&content_root, &link_path);
        let _ = std::fs::remove_dir_all(&dir);
        assert_eq!(result, Err(AssetPathError::NotUnderContentRoot));
    }

    #[test]
    fn package_name_should_strip_object_suffix_when_present() {
        let path = AssetPath::new("/Game/Characters/BP_Player").unwrap();
        let suffixed = AssetPath(format!("{}.BP_Player", path.as_str()));
        assert_eq!(suffixed.package_name(), "/Game/Characters/BP_Player");
    }

    #[test]
    fn package_name_should_return_full_path_when_no_suffix() {
        let path = AssetPath::new("/Game/Characters/BP_Player").unwrap();
        assert_eq!(path.package_name(), "/Game/Characters/BP_Player");
    }

    #[test]
    fn is_ofpa_path_should_return_true_for_external_actors_segment() {
        assert!(is_ofpa_path(
            "/Game/Maps/__ExternalActors__/MyMap/SomeActor"
        ));
    }

    #[test]
    fn is_ofpa_path_should_return_true_for_external_objects_segment() {
        assert!(is_ofpa_path(
            "/Game/Maps/__ExternalObjects__/MyMap/SomeObject"
        ));
    }

    #[test]
    fn is_ofpa_path_should_return_false_for_normal_asset_path() {
        assert!(!is_ofpa_path("/Game/Maps/MyMap"));
    }
}
