[package]
name                 = "uasset-lens-impact-analyzer"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
description.workspace = true
repository.workspace = true
homepage.workspace   = true
keywords.workspace   = true
categories.workspace = true
authors.workspace    = true

[dependencies]
uasset-lens-shared           = { workspace = true }
uasset-lens-dependency-graph = { workspace = true }
